### ISSUE TITLE
Missing nnet3-copy-egs-to-feats binary

### ISSUE THREAD

**Issue by eager-droid** [phonexiaresearch/VBx-training-recipe#1]
Hi, thank you for this repository. :) I tried running the training script `run.sh`, but there seems to be a binary missing.
The command `cmd = "nnet3-copy-egs-to-feats --print-args=false ark:{} ark:-{}".format(self._ark_file, cmn_command)` throws an error from [this line](https://github.com/phonexiaresearch/VBx-training-recipe/blob/5adf859d3625d4df39d0ba498dbd5dad07d62fb2/local/utils/pytorch_data.py#L158). The binary `nnet3-copy-egs-to-feats` is not available and nor is the source code. I also checked the kaldi `src/nnet3bin` folder, but there is only a `nnet3-copy-egs` binary. I tried running the training with this binary, but it was failing, when the byte stream was read from stdin. on [this line](https://github.com/phonexiaresearch/VBx-training-recipe/blob/5adf859d3625d4df39d0ba498dbd5dad07d62fb2/local/utils/pytorch_data.py#L171) Would it be possible to commit the `nnet3-copy-egs-to-feats` file to this repo so that the training could be reproduced?

**Comment by Jamiroquai88** [comment]
Hi, sorry about that, I forgot. Please see updated README.md.

**Comment by eager-droid** [comment]
great, thanks!
