### ISSUE TITLE
Missing transform.h5 file

### ISSUE THREAD

**Issue by eager-droid** [phonexiaresearch/VBx-training-recipe#2]
Hi, I managed to reproduce the training pipeline. I successfully created the `final.onnx` and `plda` files. I would like to try the checkpoint in the vbx diarization, but I am missing the file `transform.h5` and it does not get created during training. Could you please explain how to get this file or where it should be created? Thank you.

**Comment by Jamiroquai88** [comment]
Hi, sorry, I forgot to close the issue. Training of `transform.h5` was added recently, if you are gonna face some issues, let me know.

**Comment by janvainer** [comment]
Thanks! :)

**Comment by eager-droid** [comment]
Thanks!
