### ISSUE TITLE
 telephone codec

### ISSUE THREAD

**Issue by wbgxx333** [phonexiaresearch/VBx-training-recipe#5]
thank you for this wonderful contribution.

i read the paper,"https://arxiv.org/pdf/2012.14952.pdf"*(F. Landini, J. Profant, M. Diez, L. Burget: Bayesian HMM clustering of x-vector sequences (VBx) in speaker diarization: theory, implementation and analysis on standard tasks).

the 8kHz:Any wide-band data used were
downsampled to 8 kHz and passed through a telephone codec.
i want to know what is the telephone codec.maybe use the g711 to encode and decode?

thank you very much.

**Comment by Jamiroquai88** [comment]
Hi, this was a mix of telephone codecs, maybe @MichalKlco can specify.

**Comment by wbgxx333** [comment]
thank you .and i will wait the answer.

**Comment by MichalKlco** [comment]
Hi, we randomly applied one of the following codec (encoder and decoder) on each audio recording:

- AMR
- G.711
- G.726
- GSM-FR
- GSM-EFR

**Comment by wbgxx333** [comment]
thank you very much.
